### ISSUE TITLE
Game crashes when loading existing saves

### ISSUE THREAD

**Issue by igorljubuncic** [mmtrt/cncra2yr#3]
A consistent and reproducible issue:

- Play CNCRA2YR, save the mission. Exit the game.

- Start the game, select Skirmish, then when a new mission launches, select menu > load.

- CNCRA2YR freezes at this point (internal error).

I don't see any useful logs to add to this issue.

**Comment by mmtrt** [comment]
Known issue which is already stated in readme 63ae8860c1d43c5a324c7e926320fb9208a26c0d , can you post contents of `EXCEPT_CNCNET.TXT` if that file exist after game crash.

**Comment by FunkyFr3sh** [comment]
This doesn't seem to be a crash related to the snap, there are many logs of this crash in the database (some already from 2017). So I think this can be closed since it's not related.

I'm not working on YR on cncnet (only on the other games...) but I will ask around about this crash and see if there is a known solution for it and post here again.
